# Generated by Django 2.1.12 on 2019-11-25 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0042_auto_20190913_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 5, 211397)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 5, 211397)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 5, 219447)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 5, 219447)),
        ),
        migrations.AlterField(
            model_name='uregiser',
            name='pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
