# Generated by Django 2.1.12 on 2019-11-25 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0043_auto_20191125_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 50, 168412)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 50, 168412)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 50, 168412)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 22, 42, 50, 168412)),
        ),
        migrations.AlterField(
            model_name='uregiser',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
